project:
  type: website
  output-dir: docs
  
website:
  title: ""
  navbar:
    logo: images/isbs10logo_lr.png
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: right

editor: visual

