project:
  type: website
  output-dir: docs
  
website:
  title: ""
  navbar:
    logo: images/isbs10logo_lr.png
    pinned: true
    right:
      - text: Register
    #    href: "https://beachsymposium.org"""
        target: _blank

      - text: Submit abstract
    #    href: https://beachsymposium.org
        target: _blank
  
  sidebar:
    style: docked
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: callforabstracts.qmd
      - href: registration.qmd
      - href: iprogramme.qmd
      - href: workshopprep.qmd
      - href: proceedings.qmd
      - href: accommodation.qmd
      - href: logistics.qmd
      - href: tourism.qmd
      - href: merchandise.qmd
      - href: outreach.qmd
      - href: isbsarchive.qmd
      - href: contactus.qmd
      

format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: right

editor: visual

