---
title: "Call for abstracts"
---

[**Sandy beaches as threatened social-ecological systems: addressing local to global challenges through actionable pathways for change**]{.text-primary style="font-size: 1.4rem;"}

The theme for ISBS10 links back to the theme of the first symposium in 1983, ‘Sandy beaches as ecosystems’, and highlights the advances in our understanding of sandy shores over the past four decades. It also acknowledges the deteriorating state of beaches worldwide, and the task that lies ahead of us to work together at multiple scales to secure beaches as diverse and productive ecosystems for current and future generations to enjoy.

## Contribution formats

The first three days of the symposium will comprise talks and poster sessions. We will be offering contributions of different lengths to keep the programme dynamic. You will have the option to select your top two preferences for a contribution format when you submit your abstract. To advertise the posters, we will also have ‘lightning rounds’ of very short talks with no questions (if you have questions, you can ask the presenter during the poster sessions). The final contribution format per talk will be allocated based on the recommendations of the scientific committee during the abstract review process.

::: column-margin
Since there is only one option for a poster, if you want to present a poster and not be eligible for a talk, select the poster option twice as your preferred contribution format when you submit your abstract.
:::

- 15 min talk + 5 min for questions

- 12 min talk + 3 min for questions

- 7 min talk + 3 min for questions

- Poster + 2 min talk

## Topics

**You can submit your abstract under one of the following topics**

- Biodiversity patterns (species, habitats, ecosystems)

- Ecological processes and ecosystem services

- Pressures and impacts

- Human dimensions and social-ecological systems

- Policy, conservation, and management (includes coastal engineering, nature-based solutions)

- Other

## Submission guidelines

The online abstract portal has fields where you can add authors and their affiliations, and type (or paste) your abstract text. **Note:** the system works by adding all affiliations at the top of the page, and then allocating the affiliations to each author based on the number of the affiliation. View the abstract submission guide below for an illustrated example.

The word limit for titles is **30 words**, and for the abstract text is **250 words**. Please also include a short bio for the presenting author (max **70 words**).

You can save a draft of your abstract and log back in at a later stage to finish the submission. Your draft abstract will be saved under the 'My Abstracts' tab, and can be accessed there.

You will receive a confirmation email of your abstract submission.

**The deadline for submissions is 28 February 2027.** We are opening the call early to allow plenty of time for you submit your abstract and apply for conference funding (which often requires confirmation of a submitted abstract).

If you have any technical queries regarding abstract submission, please email the [technical team](contactus.qmd).

[Submission guide](https://airdrive.eventsair.com/eventsairwesteuprod/production-easternsun-public/d157578a3a444e7aa351da8a9541ea95){.btn .btn-secondary target="_blank" rel="noopener noreferrer"} [Submit now](https://easternsun.eventsair.com/2027-sandy-beach-symposium/call-for-abstracts){.btn .btn-secondary target="_blank" rel="noopener noreferrer"}
